GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAwNjg4NDAsImV4cCI6MTYzMDA2ODg3MCwiYXVkIjoiNjEyOGUwNjgxYWIxNzE4OThhOTczNTA1IiwiaXNzIjoiY29kZXdpdGhyb3NoYW4uY29tIn0.b6dDfIc8EnNSvjN29GgUn1RF7hmECPA35bHzJtnFlBQ


###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "5@gmail.com",
    "password": "123"
}


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "bye@gmail.com",
    "password": "bye"
}

###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAwNTI4ODAsImV4cCI6MTYzMDA1MzAwMCwiYXVkIjoiNjEyOGEyMTBkNTEwYzc0ODQwOTllYzRlIiwiaXNzIjoiY29kZXdpdGhyb3NoYW4uY29tIn0.ES6uETfccf3djssRuexMur-IjaFnCH0aEhGN_VPmdsI"
}

###
DELETE http://localhost:3000/auth/logout

### demo-verification-branch

POST http://localhost:3000/auth/verify/email/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAwNzI3NTMsImV4cCI6MTYzMDA3Mjc4MywiYXVkIjoiNjEyOGU4YTM4OGY1MGY5M2Q3ZDAyYTdmIiwiaXNzIjoiY29kZXdpdGhyb3NoYW4uY29tIn0.764YALJd7m6RPahVE9utk2tbAGe81bqcn9jbq-W_4Uk

### when route doesn't exist
GET http://localhost:3000/abc

